version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/
      - static:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./.env.dev
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && daphne server.asgi:application -b 0.0.0.0"

  nginx:
    restart: always
    build: ./nginx/
    volumes: 
      - static:/usr/src/app/static
    links:
      - web
    ports:
      - "80:80"

volumes: 
  static: